### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Tatsh** [lockgraph/yarn-audit-fix#347]
I am using Yarn 4.5.0 and here is the output:

```
 $ yarn yarn-audit-fix 
Resolve bins
Runtime digest

  isMonorepo false
  bins 
    yarn yarn
    npm npm
  
  versions 
    node v22.10.0
    npm 10.9.0
    yarn 4.5.0
    yaf 10.1.0
    yafLatest 10.1.0
  
  temp /tmp/tempy-43321eb8d549d151190d8b1b6a48a16dLcQP4a
  cwd /home/tatsh/dev/misc-scripts
  flags 
    flow patch
    npm-path system
  

Verifying package structure...
Preparing temp assets...
Patching yarn.lock with audit data...
invoke yarn npm audit --all --json --recursive
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Be (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:407)
    at ie (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:375)
    at Object.qe [as _audit] (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:1568)
    at le (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:1672)
    at ye (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:4177)
    at Te (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:5374)
    at Function.he [as sync] (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:5473)
    at file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:7692
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
Failure!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Be (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:407)
    at ie (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:375)
    at Object.qe [as _audit] (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:1568)
    at le (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:1672)
    at ye (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:4177)
    at Te (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:5374)
    at Function.he [as sync] (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:5473)
    at file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:7692
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Be (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:407)
    at ie (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:375)
    at Object.qe [as _audit] (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:1568)
    at le (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:1672)
    at ye (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:4177)
    at Te (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:5374)
    at Function.he [as sync] (file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:5473)
    at file:///home/tatsh/dev/misc-scripts/node_modules/yarn-audit-fix/target/esm/cli.mjs:10:7692
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)

Node.js v22.10.0
```

**Comment by prudloff-insite** [comment]
I can also reproduce this with Yarn 4.5.1 and yarn-audit-fix 10.1.1 when Yarn does not report any vulnerability.

**Comment by antongolub** [comment]
Fixed in v11. This was the parser choking on `yarn audit --json` output. v11 doesn't spawn yarn audit at all — advisories come straight from the registry's bulk endpoint, keyed off the parsed lockfile.
